name: 'Setup'
description: 'Sets up the repository'
runs:
  using: 'composite'
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
      with:
        cache: true

    - name: Install Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        cache: pnpm
        node-version: 24

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile

    - name: Generate api typings
      shell: bash
      run: pnpm graphql:gen
