// Do not edit this file. It was auto-generated by saveApiMocks.ts
import { b_80BAL_20WETHMock } from './b_80BAL_20WETHMock'
import { osETH_wETH_BPTMock } from './osETH_wETH_BPTMock'
import { b_50sDAI_50wstETHMock } from './b_50sDAI_50wstETHMock'
import { v2SepoliaStableWithERC4626Mock } from './v2SepoliaStableWithERC4626Mock'
import { bCoW_50WETH_50GNOMock } from './bCoW_50WETH_50GNOMock'
import { rsETH_hgETHMock } from './rsETH_hgETHMock'
import { v3SepoliaNestedBoostedMock } from './v3SepoliaNestedBoostedMock'
import { aave_USDC_USDTMock } from './aave_USDC_USDTMock'
import { b_csUSDL_steakUSDCMock } from './b_csUSDL_steakUSDCMock'
import { aGNO_sDAIMock } from './aGNO_sDAIMock'
import { partialBoostedSepoliaWethStataUsdtMock } from './partialBoostedSepoliaWethStataUsdtMock'
import { b_csUSDC_csUSDLMock } from './b_csUSDC_csUSDLMock'
import { staBAL3_WETH_WBTC_BPTMock } from './staBAL3_WETH_WBTC_BPTMock'
import { b_auraBAL_STABLEMock } from './b_auraBAL_STABLEMock'
import { aave_USDC_Aave_GHOMock } from './aave_USDC_Aave_GHOMock'
import { Pool } from '../../pool.types'

export const allApiMocks: Pool[] = [
  b_80BAL_20WETHMock,
  osETH_wETH_BPTMock,
  b_50sDAI_50wstETHMock,
  v2SepoliaStableWithERC4626Mock,
  bCoW_50WETH_50GNOMock,
  rsETH_hgETHMock,
  v3SepoliaNestedBoostedMock,
  aave_USDC_USDTMock,
  b_csUSDL_steakUSDCMock,
  aGNO_sDAIMock,
  partialBoostedSepoliaWethStataUsdtMock,
  b_csUSDC_csUSDLMock,
  staBAL3_WETH_WBTC_BPTMock,
  b_auraBAL_STABLEMock,
  aave_USDC_Aave_GHOMock
]
