import { defineRecipe } from '@chakra-ui/react'

export const buttonRecipe = defineRecipe({
  base: {
    borderRadius: 'lg',
    letterSpacing: '-0.02em',
    cursor: 'pointer',
    _disabled: {
      background: 'background.level3',
      border: '1px solid',
      borderColor: 'border.base',
      color: 'grayText',
    },
    _hover: {
      textDecoration: 'none',
      _disabled: {
        background: 'background.level3',
      },
    },
  },
  variants: {
    variant: {
      primary: {
        color: 'font.dark',
        background: 'background.button.primary',
        backgroundPosition: '100% 0',
        backgroundSize: '100% 100%',
        transition: '0.3s ease-in-out',
        boxShadow: '0 3px 20px hsla(245, 97%, 76%, 0.4)',
        _hover: {
          shadow: 'sm',
          backgroundSize: '120% 100%',
          color: 'font.dark',
          boxShadow: '0 3px 20px hsla(9, 85%, 71%, 0.4)',
          _disabled: { boxShadow: 'none' },
        },
      },
      secondary: {
        color: 'font.dark',
        background: 'background.button.secondary',
        boxShadow: '0 3px 20px hsla(33, 58%, 76%, 0.4)',
        _hover: {
          shadow: 'sm',
          color: 'font.dark',
          boxShadow: '0 3px 20px hsla(32, 43%, 82%, 0.5)',
          _disabled: { boxShadow: 'none' },
        },
      },
      tertiary: {
        background: 'background.level3',
        color: 'font.primary',
        shadow: 'md',
        _hover: { shadow: 'sm' },
        _active: { background: 'background.level2', shadow: 'none' },
      },
      maxContrast: {
        bg: 'font.maxContrast',
        color: 'font.maxContrastOpposite',
        shadow: '2xl',
        _hover: { shadow: '0' },
      },
      gold: {
        background: 'background.gold',
        color: 'white',
        shadow: '2xl',
        _hover: { shadow: 'sm' },
        _dark: { color: 'font.dark' },
      },
      goldSecondary: {
        background: 'background.gold',
        backgroundClip: 'text',
        border: '1px solid transparent',
        borderColor: 'red',
        color: 'font.gold',
        _dark: { color: 'font.gold' },
      },
      danger: {
        background: 'red.400',
        color: 'font.dark',
        shadow: 'md',
        _hover: { background: '#E67A66', shadow: 'lg' },
        _active: { background: '#D96B57', shadow: 'sm' },
        _disabled: { background: '#F48975', opacity: 0.6, shadow: 'none' },
      },
      solid: {
        color: 'text-body',
        bg: 'background.level2',
        _hover: { bg: 'background.level1' },
      },
      'tx-gas': {
        background:
          'linear-gradient(to top right, var(--chakra-colors-blue-300) 0%, #D7CBE7 50%, #EAA879 100%)',
        borderTop: '2px solid',
        borderColor: 'purple.200',
        color: 'black',
      },
      buttonGroupInactive: {
        backgroundColor: 'transparent',
        height: 'fit-content',
        width: 'fit-content',
        shadow: 'none',
        px: '2',
        py: '1.5',
        fontSize: 'xs',
        color: 'font.secondary',
        fontWeight: 'bold',
        borderRadius: '4px',
        _hover: {
          color: 'font.maxContrast',
          transform: 'none',
          _disabled: { background: 'transparent', color: 'font.secondary' },
        },
        _dark: {
          color: 'font.secondary',
          _hover: {
            color: 'font.maxContrast',
            _disabled: { color: 'font.secondary' },
          },
        },
        _disabled: { backgroundColor: 'transparent', border: 0 },
      },
      buttonGroupActive: {
        background: 'background.button.secondary',
        height: 'fit-content',
        width: 'fit-content',
        px: '2',
        py: '1.5',
        fontSize: 'xs',
        color: 'gray.700',
        fontWeight: 'bold',
        borderRadius: '4px',
        _hover: { transform: 'none' },
        _dark: { color: 'background.level3' },
      },
      buttonGroupActiveGray: {
        background: 'white',
        height: 'fit-content',
        width: 'fit-content',
        px: '2',
        py: '1.5',
        fontSize: 'sm',
        color: 'white',
        fontWeight: '700',
        borderRadius: '4px',
        _hover: { transform: 'none' },
        _dark: { color: 'background.level3' },
      },
      buttonGroupInactiveGray: {
        background: 'white',
        height: 'fit-content',
        width: 'fit-content',
        px: '2',
        py: '1.5',
        fontSize: 'sm',
        color: 'gray.700',
        fontWeight: '500',
        borderRadius: '4px',
        _hover: { transform: 'none' },
        _dark: { color: 'gray.400' },
      },
      buttonGroupInactiveCompact: {
        backgroundColor: 'transparent',
        height: '18px',
        width: 'fit-content',
        shadow: 'none',
        px: '1.5',
        py: '0',
        fontSize: 'xs',
        color: 'font.secondary',
        fontWeight: 'bold',
        borderRadius: '4px',
        _hover: { color: 'font.maxContrast', transform: 'none' },
      },
      buttonGroupActiveCompact: {
        background: 'transparent',
        height: '18px',
        px: '1.5',
        py: '0',
        fontSize: 'xs',
        color: 'font.dark',
        fontWeight: 'bold',
        borderRadius: '4px',
      },
    },
    size: {
      xxxs: { h: '24px', px: '0.5' },
      xxs: { h: { base: '24px', md: '26px' }, px: '2' },
      xs: { h: { base: '28px', md: '32px' }, px: '2' },
      sm: { h: { base: '32px', md: '36px' }, px: '2' },
      md: {
        h: { base: '36px', md: '40px' },
        fontSize: { base: '0.875rem', md: '1rem' },
        px: { base: '2', md: '3' },
      },
      lg: { h: { base: '40px', md: '48px' }, px: { base: '2', md: '3' } },
    },
  },
})
