import { Address } from 'viem'
import { getPoolMock } from './getPoolMock'
import { GqlChain } from '@repo/lib/shared/services/api/generated/graphql'
import { Pool } from '../PoolProvider'
import fs from 'fs'
import path from 'path'
import { lowerFirst } from 'lodash'

/**
 * Fetches a pool from the API and saves it as a mock file in the api-mocks directory.
 */
export async function savePoolMock(poolId: Address, chain: GqlChain, fileName?: string) {
  const pool = (await getPoolMock(poolId, chain)) as Pool
  const poolJson = JSON.stringify(pool, null, 2)

  const poolVarName = fileName || createPoolVarName(pool)
  const apiMocksDir = path.join(__dirname, 'api-mocks')
  const filePath = path.join(apiMocksDir, `${poolVarName}.ts`)

  fs.writeFileSync(filePath, createPoolMockFromTemplate(poolVarName, poolJson), 'utf-8')

  // Uncomment to debug
  // console.log(`${poolVarName} pool mock saved to ${filePath}`)
}

function createPoolMockFromTemplate(poolVarName: string, poolJson: string) {
  return `
  // Do not edit this file. It was auto-generated by saveApiMocks.ts

  import { Pool } from '../../PoolProvider'

  export const ${poolVarName} =
${poolJson} as unknown as Pool
`
}

function createPoolVarName(pool: Pool) {
  return lowerFirst(pool.symbol.replace(/[^a-zA-Z0-9]/g, '_'))
}
